# Generated by Django 5.1 on 2024-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('major', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('CIV', 'Civil Engineering'), ('MEC', 'Mechanical Engineering')], max_length=3)),
            ],
        ),
    ]
